 language: scala
 scala:
   - "2.10.4"
 jdk:
   - oraclejdk7
 env:
   global:
     - LIB_VERSION=$TRAVIS_BUILD_NUMBER
     - secure: "hlK4HAq3CGCJioDT9HulnTFWUW65B4UbJNmW90of/xl2KGXtBNeYdYEeHysldjXFicDLcncYEMKqD6JmsFlz1l/fZHlVaEP3rLWbseA9jsH+tgS2Wi+Gkp+n9yDSaqcgDRdie5rwKrcFxD13b1XbKNh4IYEAtC4JbD4vLpWJuKc="
 script: sbt test publish
 after_success: ./publish/publish.sh
