 language: scala
 scala:
   - "2.10.4"
 jdk:
   - oraclejdk7
 env:
   global:
     - secure: NQ6OAT29oas9+H/9xvb4w/D/5/pczRXCNeBxIr9GQV1SEnKmwgu/RQfe+H31TWnvS9GZ6TbyPRctD1DI0smOFz294h18uuijOI02tJby0EGGyWZakHF5VAdQX0JwvEPHT0HgB0hi3nsSahDnLAwV/Dzm1SZ8h+Ez9ct1AVo/v+A=
     - LIB_VERSION=$TRAVIS_BUILD_NUMBER
 before_script:
   - echo "$TRAVIS_SECURE_ENV_VARS"
   - echo "$TRAVIS_PULL_REQUEST"
   - echo "$TRAVIS_BRANCH"
   - echo "$TRAVIS_COMMIT"
   - echo "$TRAVIS_REPO_SLUG"
 script: sbt test publish
 after_success: ./publish/publish.sh
